on: push

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install packages
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Unit Tests
        run: npm run test:unit

      - name: E2E Tests
        run: npm run test:e2e -- --headless
        continue-on-error: true #TODO: remove

      - name: Build App
        if: contains(github.ref, 'master')  # only on master branch
        run: npm run build

      - name: Deploy
        if: contains(github.ref, 'master')  # only on master branch
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -azvP --delete
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USERNAME }}
          remote_key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          path: 'dist/'
          remote_path: ${{ secrets.REMOTE_PATH }}
